name: tp_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
#  sdk: ">=2.16.2 <3.0.0"
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cupertino_list_tile: ^0.2.1
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  flutter_svg: ^1.0.3
  circle_list: ^1.0.5

  animated_splash_screen: ^1.2.0
  firebase_auth: ^3.3.12
  firebase_dynamic_links: ^4.2.0
  cloud_functions: ^3.2.13
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.10
  firebase_core: ^1.14.0
  provider: ^6.0.2
  multiselect: ^0.0.4
  image_picker: ^0.8.5+3
  firebase_messaging: ^11.2.12
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  flutter_phone_direct_caller: ^2.1.0
  url_launcher: ^6.0.20
  

  rflutter_alert: ^2.0.2
  audioplayers: ^0.20.1
  open_file: ^3.2.1
  overlay_support: ^2.0.1
  
  
  
 

  share: ^2.0.4
  permission_handler: ^9.2.0
  #share_plus: ^4.0.4
  timeago: ^3.2.2
  video_thumbnail: ^0.5.0
  file_picker: ^4.5.1
  gallery_saver: ^2.3.2
  uuid: ^3.0.6
  dio: ^4.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.3.0
  infinite_scroll_pagination: ^3.1.0
  auto_size_text: ^3.0.0
 
  percent_indicator: ^4.2.1
  record: ^4.1.1
  device_info_plus: ^3.2.3
  
 
  flutter_bloc: ^8.0.1
  flutter_sound: ^9.2.12
  linkify: ^4.1.0
  loading_overlay: ^0.3.0
  photo_view: ^0.14.0
  animations: ^2.0.2
  http: ^0.13.4
  device_info: ^2.0.0
  package_info: ^2.0.0


 
  
  
  sqflite: ^2.0.2+1
  pdf_viewer_plugin: ^2.0.1
  video_player: ^2.4.2
  readmore: ^2.1.0
  flutter_local_notifications: #^9.6.0
  
  flutter_launcher_icons: ^0.9.2
  path_provider: ^2.0.0
  flutter_email_sender: ^5.1.0
 
 
   
 



  
  

  
 
  



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.4



  flutter_lints: ^1.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
#assets:
 # - assets/font/soleil.png
  uses-material-design: true

  assets:
  - assets/admin.json
  - assets/pays.json
  #- assets/images/soleil.png
  - assets/images/agri_w.svg
  - assets/images/agri_b.svg
  - assets/images/sun2.svg
  - assets/images/ana.jpg
  - assets/images/rice.jpg
  - assets/images/ma.jpg
  - assets/images/marai.jpg 
  - assets/images/soja.jpg
  - assets/images/preview.jpg
  - assets/images/agri.png
  - assets/images/agri2.png
  - assets/images/agri3.png
  - assets/images/agri1.png
  - assets/images/logo.png

  fonts:
    - family: Cambria
      fonts:
        - asset: assets/font/cambria.ttf
        - weight: 100
    - family: Calibri 
      fonts:
        - asset: assets/font/calibril.ttf
        - weight: 100
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-ExtraLight.ttf
        - weight: 100
        - asset: assets/font/Poppins-ExtraBold.ttf
        - weight: 100
        - asset: assets/font/Poppins-Italic.ttf
        - weight: 100
        - asset: assets/font/Poppins-SemiBold.ttf
        - weight: 100
        - asset: assets/font/Poppins-Medium.ttf
        - weight: 100
        - asset: assets/font/Poppins-Regular.ttf
        - weight: 100
        - asset: assets/font/Poppins-Black.ttf
        - weight: 100
        - asset: assets/font/Poppins-Bold.ttf
        - weight: 100
        - asset: assets/font/Poppins-Thin.ttf
        - weight: 100

       # - asset: packages/awesome_package/fonts/Raleway-Regular.ttf
        #- asset: packages/awesome_package/fonts/Raleway-Italic.ttf
 
          
         




  # To add assets to your application, add an assets section, like this:
   #assets:
    # - assets/images/soleil.png
   #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
   #fonts:
         #- asset: fonts/
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
